ABSignV2/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ABSignV2;

namespace ABSignV2.Controllers
{
    public class ImagesController : Controller
    {
        private AbSignV2Entities db = new AbSignV2Entities();

        // GET: Images
        public ActionResult Index()
        {
            var images = db.Images.Include(i => i.Sign);
            return View(images.ToList());
        }

        // GET: Images/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        // GET: Images/Create
        public ActionResult Create()
        {
            ViewBag.SignID = new SelectList(db.Signs, "SignID", "SignName");
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImageID,ImageBin,SignID")] Image image, HttpPostedFileBase image1)
        {
            if (ModelState.IsValid)
            {
                image.ImageBin = new byte[image1.ContentLength];
                image1.InputStream.Read(image.ImageBin, 0, image1.ContentLength);
                //string id = User.Identity.GetUserId(); //saves currently logged in user id to string id
                db.Images.Add(image);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SignID = new SelectList(db.Signs, "SignID", "SignName", image.SignID);
            return View(image);
        }

        // GET: Images/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            ViewBag.SignID = new SelectList(db.Signs, "SignID", "SignName", image.SignID);
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ImageID,ImageBin,SignID")] Image image)
        {
            if (ModelState.IsValid)
            {
                db.Entry(image).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SignID = new SelectList(db.Signs, "SignID", "SignName", image.SignID);
            return View(image);
        }

        // GET: Images/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Image image = db.Images.Find(id);
            db.Images.Remove(image);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ABSignV2/Views/Images/Create.cshtml
@model ABSignV2.Image

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageBin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="image1" name="image1" />
                @*@Html.EditorFor(model => model.ImageBin, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.ImageBin, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ABSignV2/Views/Images/Delete.cshtml
@model ABSignV2.Image

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageBin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageBin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sign.SignName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sign.SignName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ABSignV2/Views/Images/Details.cshtml
@model ABSignV2.Image

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageBin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageBin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sign.SignName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sign.SignName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ImageID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ABSignV2/Views/Images/Edit.cshtml
@model ABSignV2.Image

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImageID)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageBin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageBin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageBin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SignID, "SignID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SignID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SignID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ABSignV2/Views/Images/Index.cshtml
@model IEnumerable<ABSignV2.Image>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageBin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sign.SignName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @if (item.ImageBin != null)
                {
                    var base64 = Convert.ToBase64String(item.ImageBin);
                    var imgsrc = string.Format("data:image/jpeg; base64,{0}", base64);
                    <img src="@imgsrc" style="max-width:100px;max-height:100px;" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sign.SignName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ImageID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ImageID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ImageID })
            </td>
        </tr>
     }
    

</table>